services:
  db:
    image: postgres
    container_name: clinica_postgres
    ports:
      - "5432:5432"  # expõe para o host
    environment:
      POSTGRES_DB: clinica_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
